### PR TITLE
Update jsonrpsee to 0.20

### PR DESCRIPTION
**Pull request by fl0rek**
Changed minimum jsonrpsee version for `rpc` to `0.20`, then updated dependency with `cargo update -p jsonrpsee --precise 0.20.0`.
 Tests pass on my machine.

### CODE REVIEW

**Review by oblique — APPROVED** [review]
lgtm

**Review by zvolin — APPROVED** [review]
lgtm

**Comment by zvolin** [comment]
@fl0rek could you set up a commit signing on your side and amend the commit to include the signature?

**Comment by fl0rek** [comment]
@zvolin fixed signature, github seems to be happy about it now :)

**Pull request merged**
