### PR TITLE
feat(types): Add `wasm-bindgen` feature flag

### LINKED ISSUE #131: CosmWasm VM fails when tendermint's `wasm32-bindgen` feature is enabled for `celestia-types`
## Problem Statement

We are currently engaged in the development of an IBC light client for Sovereign SDK blockchains. In this process, the `celestia-types` crate is employed for importing relevant types. 
I have encountered an issue during the compilation of our CosmWasm smart contract with the `wasm32-unknown-unknown` target. The contract relies on `celestia-types` as one of its dependencies, and during compilation, the `celestia-types` is compiled with the [`wasm32-bindgen` feature](https://github.com/eigerco/celestia-node-rs/blob/69647d66c489b4b7df3cf1a7df24c1c79abe3111/types/Cargo.toml#L30) enabled for the `tendermint-rs` dependency. This leads to an error when the CosmWasm VM attempts to load the contract (this [issue](https://github.com/informalsystems/sovereign-ibc/issues)). Locally, I could manage this issue by disabling the `wasm32-bindgen` feature and the compiled Wasm file works as expected.

## Proposal

To not enforce the `wasm32-bindgen` feature for the wasm32 targets. Instead, defining a new feature, such as `wasm-bindgen = ["tendermint/wasm-bindgen"]` to selectively enable the `wasm32-bindgen` feature where necessary.

## Side Question
Additionally, I noticed there is a `wasm-bindgen` feature for the `time` dependency so we could have e.g. `wasm-bindgen = ["time/wasm-bindgen"]` instead of [this](https://github.com/eigerco/celestia-tendermint-rs/blob/ef58b85e3e8b35b0f94b822d3996613539dcddd7/tendermint/Cargo.toml#L65) within the `celestia-tendermint-rs`, so the unit tests would pass too. Was there any specific reason for introducing the `Instant` dependency in this context?

### PR DESCRIPTION
**Pull request by oblique**
fixes #131

### CODE REVIEW

**Review by zvolin — APPROVED** [review]
looks good

**Comment by Farhad-Shabani** [comment]
Thanks for this PR! Only one more step remains: 
Enabling the [`Instant`](https://github.com/eigerco/celestia-tendermint-rs/blob/ef58b85e3e8b35b0f94b822d3996613539dcddd7/tendermint/Cargo.toml#L56-L57) dependency in the `celestia-tendemint-rs` **only** with the `wasm-bindgen` feature. Therefore places like [here](https://github.com/eigerco/celestia-tendermint-rs/blob/ef58b85e3e8b35b0f94b822d3996613539dcddd7/tendermint/src/time.rs#L74) we should have:

```rust
    #[cfg(all(feature = "clock", target_arch = "wasm32", feature = "wasm-bindgen"))]
```

**Comment by oblique** [comment]
@Farhad-Shabani Thanks. Just open PR https://github.com/eigerco/celestia-tendermint-rs/pull/14

**Review by fl0rek — APPROVED** [review]
🎸

**Pull request merged**
